Repository Artemiskgg1/NexaSite, pull requests merged in 2024-10, with the labels that each got.

#37 Made the images responsive and dynamic
  index.html
  style.css
Labels: enhancement, hacktoberfest

#50 fix Replace default cursor with circle #45
  index.html
Labels: duplicate

#56 Fix: Style of cutom cursor can be easily changed with config.json
  CSS/variables.css
  config.json
  index.html
  pages/about.html
  pages/config.json
  pages/contact.html
  pages/footer.html
  pages/header.html
  pages/services.html
  script.js
  style.css
Labels: bug, hacktoberfest-accepted

#63 changes done in navbar, contact-us, about-us page
  CSS/about.css
  CSS/contact.css
  index.html
  pages/about.html
  pages/contact.html
  style.css
Labels: hacktoberfest-accepted

#62 fix image overflow
  index.html
  style.css
Labels: hacktoberfest-accepted

#65 Revert "changes done in navbar, contact-us, about-us page"
  CSS/about.css
  CSS/contact.css
  index.html
  pages/about.html
  pages/contact.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#66 Filled the empty space under the office section
  CSS/contact.css
Labels: hacktoberfest-accepted

#68 header-service-fix
  CSS/services.css
  pages/header.html
  pages/services.html
  style.css
Labels: hacktoberfest-accepted

#71 added news page
  index.html
  pages/news.html
Labels: hacktoberfest-accepted

#72 Copyright label added in footer section
  index.html
  style.css
Labels: hacktoberfest-accepted

#82 updating the contributing.md file
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#76 Added slogan in the footer section
  index.html
  pages/services.html
  style.css
Labels: hacktoberfest-accepted

#80 Fixed irregular scaling in about us section
  style.css
Labels: hacktoberfest-accepted

#81 adding all pages with routing
  index.html
  pages/casestudies.html
  pages/header.html
  pages/manu.html
  pages/research.html
Labels: hacktoberfest-accepted

#84 fixes #69 : UI of products & Services page is Enhanced
  CSS/services.css
  pages/services.html
Labels: hacktoberfest-accepted

#88 Adding login page and also changing the structue of the site.....
  CSS/contact.css
  CSS/login.css
  index.html
  pages/login.html
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#89 Revert "Adding login page and also changing the structue of the site....."
  CSS/contact.css
  CSS/login.css
  index.html
  pages/login.html
  style.css
Labels: hacktoberfest-accepted

#92 [Fixed]: This code fixes the Issue-#87
  index.html
  style.css
Labels: hacktoberfest-accepted

#94 Made [Footer] consistent across different pages.
  CSS/footer.css
  pages/footer.html
Labels: hacktoberfest-accepted

#95 FIXED : nexasite logo on footer should take to the top #77 #93
  index.html
  style.css
Labels: hacktoberfest-accepted

#97 [Fixed]: This updated code fixes the unusual size of the read more buttton
  index.html
  style.css
Labels: hacktoberfest-accepted

#98 Fix in service page
  pages/services.html
Labels: hacktoberfest-accepted

#100 social links added
  index.html
  pic/facebook.svg
  pic/instagram.svg
  pic/linkedin.svg
  pic/x.svg
  pic/youtube.svg
  style.css
Labels: hacktoberfest-accepted

#105 Update README.md
  CSS/footer.css
  README.MD
  index.html
  pages/footer.html
  pages/news.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#108 Shreelusantoshbranch
  README.MD
Labels: hacktoberfest-accepted

#110 added scroll to top button to pages of the site
  index.html
  pages/about.html
  pages/casestudies.html
  pages/contact.html
  pages/manu.html
  pages/news.html
  pages/research.html
  pages/services.html
  script.js
  style.css
Labels: hacktoberfest-accepted

#112 Fixed Footer Styling
  CSS/footer.css
  index.html
  pages/footer.html
Labels: hacktoberfest-accepted

#114 micro interactions for cards
  CSS/services.css
  package-lock.json
  pages/services.html
Labels: hacktoberfest-accepted

#115 Created CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#118 UI Enhancements : Improve Design of News Page Cards
  CSS/news.css
  pages/news.html
Labels: hacktoberfest-accepted

#119 made about section responsive
  index.html
  style.css
Labels: hacktoberfest-accepted

#123 Enhance news card interactions
  CSS/news.css
Labels: hacktoberfest, hacktoberfest-accepted

#126 Update logo images in HTML files by making new Favicon
  index.html
  pages/footer.html
  pages/header.html
  pages/services.html
  pic/FaviconDark.svg
  pic/FaviconLight.svg
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
Labels: hacktoberfest-accepted

#131 changes made to header and the footer (made them better in ui and responsiveness)
  CSS/footer.css
  index.html
  pages/footer.html
  pages/header.html
Labels: hacktoberfest-accepted

#132 Fix: Header Spacing and Center Footer Copyright (#124)
  CSS/footer.css
  style.css
Labels: hacktoberfest-accepted

#136 Critical: Restored index.html with all necessary content
  index.html
Labels: hacktoberfest-accepted

#137 Feat: Added Scroll Bar Indicator
  index.html
  script.js
  style.css
Labels: hacktoberfest-accepted

#142 Make Service page responsive and fix footer issues
  CSS/services.css
  pages/services.html
  style.css
Labels: hacktoberfest-accepted

#144 Improved the UI of the manafacturing page
  CSS/manu.css
  pages/manu.html
Labels: hacktoberfest-accepted

#146 Improve "About Us" Page for Enhanced Visual Appeal and Professionalism
  CSS/about.css
  pages/about.html
  pic/AboutUs/mission.png
  pic/AboutUs/values.png
  pic/AboutUs/vision.png
Labels: hacktoberfest-accepted
